import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "../styles/index.scss";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { Suspense } from "react";
import Loading from "./loading";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const bauotSans = localFont({
  src: "./fonts/BauOT-Regular.ttf",
  variable: "--fonts-bauot-sans",
  weight: "100 900",
});
const bauotBold = localFont({
  src: "./fonts/BauOT-Bold.ttf",
  variable: "--fonts-bauot-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "My Music App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bauotSans.variable} ${bauotBold.variable} antialiased`}
      >
        <Navbar />
        <Suspense fallback={<Loading />}>
          <main>{children}</main>
        </Suspense>
        <Footer />
      </body>
    </html>
  );
}
