name: Deploy Site on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
          node-version: '20.x'
  
    # - name: 🔨 Build Project
    #   run: |
    #     npm install
    #     npm run build    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
       server: 198.54.125.109
       username: autodeploygithub@republicmanagement.org
       password: 4skqrBiG7+Yh
       local-dir: ./dist/
    #  server-dir: app.example.com/ 
